### ISSUE TITLE
Remove unnecessary null pointer checks

### ISSUE THREAD

**Issue by elfring** [janesma/apitrace#12]
[An extra null pointer check is not needed in functions](https://isocpp.org/wiki/faq/freestore-mgmt#delete-handles-null "Do I need to check for null before delete p?") like the following.
- [Call](https://github.com/janesma/apitrace/blob/10da296ae3ca713b6775cef07bddb5c5770ce578/lib/trace/trace_model.cpp#L39 "Destructor for Call")
- [FrameRetrace](https://github.com/janesma/apitrace/blob/c585fb2aff8cf46b7483b65390556a8891d4bdef/retrace/daemon/glframe_retrace.cpp#L99 "Destructor for FrameRetrace")
- [FrameRetraceModel](https://github.com/janesma/apitrace/blob/c585fb2aff8cf46b7483b65390556a8891d4bdef/retrace/daemon/ui/glframe_retrace_model.cpp#L87 "Destructor for FrameRetraceModel")

**Comment by janesma** [comment]
Fair enough.  I am limiting my changes to the retrace/daemon directory, so I wouldn't want to change the destructor for Call.

**Comment by elfring** [comment]
I would appreciate if the software implementation could be improved in a consistent way.

**Comment by janesma** [comment]
I hear you.  I can take your patch (or write it myself) to get rid of  unnecessary checks in FrameRetrace.  If you want to improve the upstream project (for Call) then you can submit the change to https://github.com/apitrace/apitrace and FrameRetrace will get it when it rebases to master.

**Comment by elfring** [comment]
A similar update suggestion is waiting for the corresponding software development attention also in the upstream project.
