### ISSUE TITLE
Undo/Restore

### ISSUE THREAD

**Issue by cefiar** [janesma/apitrace#16]
Would be great to have Undo functionality when editing the current frame.

eg:
- Shaders
- Uniforms
- State

Even if this is just to Restore the default values from the original frame (instead of a full Undo), that would be exceedingly useful.

**Comment by janesma** [comment]
I agree with this request and will see what I can do.  It shouldn't be too hard.

Would you want an undo for the selected renders, or a global undo for the frame?

**Comment by cefiar** [comment]
Global undo (restore frame?) is probably easiest. Undo for each section would be a nice to have, but I can live without it. :D

**Comment by janesma** [comment]
implemented on the frameretrace branch
