### ISSUE TITLE
Frame changing

### ISSUE THREAD

**Issue by cefiar** [janesma/apitrace#17]
When tracking down an issue, sometimes it's necessary to look at more than one frame.

The ability to load the next or previous frame without completely re-running FrameRetrace would be advantageous.

**Comment by janesma** [comment]
would it be acceptable to simply show renders from more than one frame in the graph?
Eg, in the open dialog, you could specify frame 100-104.

**Comment by cefiar** [comment]
That'd be fine too! Probably want to make sure there is some way to easily tell different frames apart in the metrics though.

**Comment by janesma** [comment]
I'd like to color the bars based on content.  SwapBuffers could be a special bar.  I think bars for renders that generate gl errors should be colored as well, and the errors visible in the api log.

**Comment by janesma** [comment]
Initial support is pushed to frameretrace branch.  Should work as advertised in 4267571c.  Bars don't have a different color, but that will be covered elsewhere.

https://www.pivotaltracker.com/story/show/142990513
