### ISSUE TITLE
frame allows - at start with seemingly weird results

### ISSUE THREAD

**Issue by cefiar** [janesma/apitrace#19]
Since https://github.com/janesma/apitrace/commit/4267571c04f7de3bc9645a243b46d11f526a06c0 allows targetting multiple frames, you can enter `-nnn` where `nnn` is a frame number with unpredictable results. Using `nnn-` gives an error saying to specify start and end frame.

eg: I tried -378 (tried to type 1-378 and made a typo). In my case this appears to have slowed replay by `frameretrace_server` to a crawl, even when immediately re-ran with correct parameters. The ongoing slowness eventually rectified itself after frametrace was killed and my machine was left idle for a minute.

To fix, something along the following lines probably needs to be implemented:
- Disallow - as the first character in the frame field (eg: check if frame is 0 or less?)
- If - is the first character, assume that frameretrace should start at the first frame of the trace. Note that this implies that nnn- would be valid, starting at the numbered frame and running to the end of the trace.

PS: Might be worth also adding some help to the right of the UI field for entry of the frame(s).
  eg: `[frame #] or [start frame #]-[end frame #]`

**Comment by janesma** [comment]
Thanks for checking the boundary conditions.  I put in some pretty lame
input verification, but will beef it up.

-Mark

**Comment by janesma** [comment]
I added some really basic checking.  The error message gives some help that should explain to users what is accepted.

f710f4d256c035b4f8a126a1d7fc775578037f96
OpenFile: Provide some input validation on the frame number
