### ISSUE TITLE
BarGraph: Left-right selection segfault/issues (no boundary values)

### ISSUE THREAD

**Issue by cefiar** [janesma/apitrace#21]
When navigating the bargraph with left-right:
1. Going too far to the right moves off the last entry so you need to click the bar graph again. This also spits out on console the error:
> 240:9: QML ContentItem: Binding loop detected for property "implicitWidth"
2. Going too far to the left gives the same error on console but also a segfault and the app quits:
> 240:9: QML ContentItem: Binding loop detected for property "implicitWidth"
> Segmentation fault

The code needs to check the bounds of the values and not allow the value to go outside the range that matches the entries in the bargraph.

**Comment by janesma** [comment]
I really appreciate your testing.  

fixed in 425013e87e460342924b3948a97bda4c6619a5d2
