### ISSUE TITLE
How can I make apitrace diff work on windows

### ISSUE THREAD

**Issue by AlexMeng1986** [janesma/apitrace#26]
Sir, I try to diff two traces, when I input apitrace diff  test01.trace test02.trace, there is an error that failed to execute python, how can I fix this error?

**Comment by janesma** [comment]
the diff functionality is provided by apitrace, and is not part of the work I've done in FrameRetrace.  If there are problems with it, you should ask in the upstream apitrace github.  However, I think the tool ought to work if you install python and call the script directly (scripts/tracediff.py)
